//LOGIN
export const START_LOGIN_PROCESS = 'START_LOGIN_PROCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

//LOGOUT
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';

//UI CONFIG
export const UI_CONFIG_FETCH_SUCCESS = 'UI_CONFIG_FETCH_SUCCESS';
export const UI_CONFIG_FETCH_FAILED = 'FAILED';

//POST BUZZ
export const BUZZ_POST_START = 'BUZZ_POST_START';
export const BUZZ_POST_SUCCESS = 'BUZZ_POST_SUCCESS'
export const BUZZ_POST_FAILED = 'BUZZ_POST_FAILED';

//FETCH ALL BUZZ 
export const BUZZ_FETCH_START = 'BUZZ_FETCH_START';
export const BUZZ_FETCH_SUCCESS = 'BUZZ_FETCH_SUCCESS'
export const BUZZ_FETCH_FAILED = 'BUZZ_FETCH_FAILED';

//FETCH My BUZZ 
export const MY_BUZZ_FETCH_START = 'MY_BUZZ_FETCH_START';
export const MY_BUZZ_FETCH_SUCCESS = 'MY_BUZZ_FETCH_SUCCESS'
export const MY_BUZZ_FETCH_FAILED = 'MY_BUZZ_FETCH_FAILED';

//DELETE BUZZ BY ID
export const DELETE_BUZZ_START = 'DELETE_BUZZ_START';
export const DELETE_BUZZ_SUCCESS = 'DELETE_BUZZ_SUCCESS';
export const DELETE_BUZZ_FAILED = 'DELETE_BUZZ_FAILED';

//UPDATE BUZZ
export const BUZZ_UPDATE_START = 'BUZZ_UPDATE_START'
export const BUZZ_UPDATE_SUCCESS = 'BUZZ_UPDATE_SUCCESS';
export const BUZZ_UPDATE_FAILED = 'BUZZ_UPDATE_FAILED';

//MARK LIKE ON BUZZ
export const LIKE_MARK_SUCCESS = 'LIKE_MARK_SUCCESS';
export const LIKE_MARK_FAILED = 'LIKE_MARK_FAILED';

//MARK DISLIKE ON BUZZ
export const DISLIKE_MARK_SUCCESS = 'DISLIKE_MARK_SUCCESS';
export const DISLIKE_MARK_FAILED = 'DISLIKE_MARK_FAILED';

//POST COMPLAINT
export const COMPLAINT_POST_START = 'COMPLAINT_POST_START';
export const COMPLAINT_POST_SUCCESS = 'COMPLAINT_POST_SUCCESS'
export const COMPLAINT_POST_FAILED = 'COMPLAINT_POST_FAILED';

//FETCH COMPLAINTS
export const USER_COMPLAINT_FETCH_START = 'USER_COMPLAINT_FETCH_START';
export const USER_COMPLAINT_FETCH_SUCCESS = 'USER_COMPLAINT_FETCH_SUCCESS'
export const USER_COMPLAINT_FETCH_FAILED = 'USER_COMPLAINT_FETCH_FAILED';

//FETCH COMPLAINT
export const COMPLAINT_FETCH_START = 'COMPLAINT_FETCH_START';
export const COMPLAINT_FETCH_SUCCESS = 'COMPLAINT_FETCH_SUCCESS'
export const COMPLAINT_FETCH_FAILED = 'COMPLAINT_FETCH_FAILED';

//UPDATE COMPLAINT
export const COMPLAINT_UPDATE_SUCCESS = 'COMPLAINT_UPDATE_SUCCESS'
export const COMPLAINT_UPDATE_FAILED = 'COMPLAINT_UPDATE_FAILED';

//ADD COMMENT ON COMPLAINT
export const COMMENT_ADD_SUCCESS = 'COMMENT_ADD_SUCCESS'
export const COMMENT_ADD_FAILED = 'COMMENT_ADD_FAILED';

//DELETE COMPLAINT
export const DELETE_COMPLAINT_SUCCESS = 'DELETE_COMPLAINT_SUCCESS'
export const DELETE_COMPLAINT_FAILED = 'DELETE_COMPLAINT_FAILED';

//FETCH COMPLAINTS
export const ALL_COMPLAINT_FETCH_START = 'ALL_COMPLAINT_FETCH_START';
export const ALL_COMPLAINT_FETCH_SUCCESS = 'ALL_COMPLAINT_FETCH_SUCCESS'
export const ALL_COMPLAINT_FETCH_FAILED = 'ALL_COMPLAINT_FETCH_FAILED';

//UPDATE STATUS ON COMPLAINT
export const UPDATE_STATUS_COMPLAINT_SUCCESS = 'UPDATE_STATUS_COMPLAINT_SUCCESS';
export const UPDATE_STATUS_COMPLAINT_FAILED = 'UPDATE_STATUS_COMPLAINT_FAILED';

//UPDATE CURRENT PAGE
export const UPDATE_CURRENT_PAGE = 'UPDATE_CURRENT_PAGE';

